setup:
  runtime:
    nodejs: 18
  webserver:
    locations:
      "/":
        type: node
        port: 1337
        headers:
          - pattern: "/*"
            headers:
              Access-Control-Allow-Origin: "https://content.ms3dm.tech, https://ms3dm.tech"
              Access-Control-Allow-Methods: "GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS"
              Access-Control-Allow-Headers: "Content-Type, Authorization, Origin, Accept"
              Access-Control-Allow-Credentials: "true"

  env:
    NODE_ENV: "production"
    HOST: "0.0.0.0"
    PORT: "1337"
    URL: "https://content.ms3dm.tech"
    DATABASE_CLIENT: "mysql"
    DATABASE_SSL: "false" 