# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: build

jobs:
# Please do not rename this job
  build-project:
    name: build ms3dm-strapi-backend
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: v18.x

      - name: Build Node assets
        env:
          ADMIN_JWT_SECRET: psrPy5mVKjaYoEDom8oASA==
          API_TOKEN_SALT: Jrpo+cLE4PZTPfFXU/G6PA==
          APP_KEYS: z241mK0gLbEpM+y9t5W5mw==,s9vC4Ajwtz6fRerkVawp/Q==,nTcjxP2g/MGztw9CcB496Q==,m21XpsWdAyFqPy3DK4LIAA==
          CI: true
          DATABASE_CLIENT: mysql
          DATABASE_FILENAME: tmp/data.db
          DATABASE_HOST: your_mysql_host
          DATABASE_PASSWORD: your_mysql_password
          DATABASE_PORT: 3306
          DATABASE_SSL: false
          DATABASE_USERNAME: your_mysql_username
          HOST: 0.0.0.0
          JWT_SECRET: HZH3JNuvjA4hXAIp+Rmp+w==
          PORT: 1337
          SITE_URL: ${{ inputs.site-url }}
          STRAPI_LICENSE: ZUZYK1psSEY0QUswMjgvSkR0OEFBR1RISUltdkd0eGNFUEhkZDhHNUJBM0xmeFlzV2lKbkt0SkRGeGhoYjFTcnVHMmlXeitkR3lFRDYrVXJLZHQ0L1huODNBN1FpdTU4M0d6NE1TUUNYWmx6UXBoMkx2a0lvMEVFSGZUTlpJcHZMQW1ZODgyYThjY2swa2lBWU5NTHlJZ3cvbU1OZ3ZUd21TQ0JLcXpWUDJDTGVVbzRQcllMTUcwQk5BVzZwYk5DQ0xmQ2FlNFJ4RGNWT3ZFaFpxS0UyMVJkdkZhQ0xHd1ZNRjZhTVAzYTlVcXJTTEJ6UlVaTU8vNzFXc1NrbDFIUmh0VjNJT2F0M3VlOTVoNDN1KzAvQnJlc0NVQXZKM2s5K2U3SStOY0xQbzZ0Ly9QM05XMUVhZENhUWV3ck9nL0dVZU1vMkxhY05PSFlZOEdCbHFiMG53PT0KZXlKMGVYQmxJam9pYzJsc2RtVnlJaXdpWlhod2FYSmxRWFFpT2pFM05ETXdORGMwT0RRd01EQXNJbU4xYzNSdmJXVnlTV1FpT2lKQmVubDNkVTlWWVhKUVdIaGtNemhaTnlJc0luTjFZbk5qY21sd2RHbHZia2xrSWpvaU5tOXhTVkZWWVhKUFRtbG1NMFJMZFNJc0ltbHpWSEpwWVd3aU9tWmhiSE5sTENKelpXRjBjeUk2TVN3aVptVmhkSFZ5WlhNaU9sdDdJbTVoYldVaU9pSmpiWE10WTI5dWRHVnVkQzFvYVhOMGIzSjVJaXdpYjNCMGFXOXVjeUk2ZXlKeVpYUmxiblJwYjI1RVlYbHpJam96TUgxOUxIc2libUZ0WlNJNkltTnRjeTFqYjI1MFpXNTBMWEpsYkdWaGMyVnpJaXdpYjNCMGFXOXVjeUk2ZXlKdFlYaHBiWFZ0VW1Wc1pXRnpaWE1pT2prNU9UazVPWDE5WFN3aWJHbGpaVzV6WlV0bGVTSTZJbU01WkRJNVkySXpMV0kxWWprdE5ETTNOaTA1WmpJeUxXUTRaV1JtWm1JMk5XVXlNeUo5
          TRANSFER_TOKEN_SALT: ILgNnVfH5PpGxz4GaTrtew==
        run: |
          npm install && npm run build
          npm run start

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: 92994d41-204c-47f3-802f-b24b7a73b801
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/ms3dm-strapi-backend/config.yaml
          action: upload
